name: CI/CD Pipeline

on:
  pull_request:
    types: [closed]  # KÃ­ch hoáº¡t khi PR Ä‘Æ°á»£c Ä‘Ã³ng
    branches: [ "main" ]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    outputs:
      issue_key: ${{ steps.extract.outputs.issue_key }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Issue Key
        id: extract
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          ISSUE_KEY=$(echo "$PR_TITLE" | grep -oE '[A-Z]+-[0-9]+')
          echo "issue_key=$ISSUE_KEY" >> $GITHUB_OUTPUT

      - name: Run CI tasks
        run: |
          echo "ğŸ”§ Äang cháº¡y build/test..."
          echo "âœ… Test passed"

  jira-update:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Update Jira issue status
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.JIRA_TOKEN }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data '{
              "transition": {
                "id": "3"
              }
            }' \
            https://dungssunny412.atlassian.net/rest/api/3/issue/${{ needs.build.outputs.issue_key }}/transitions

  slack-notify:
    needs: jira-update
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"âœ… Issue *${{ needs.build.outputs.issue_key }}* Ä‘Ã£ Ä‘Æ°á»£c Ä‘Ã³ng sau khi merge PR: ${{ github.event.pull_request.html_url }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
